### ISSUE TITLE
Altimeter cannot be set to STD

### ISSUE THREAD

**Issue by riotrev** [Heavy-Division/B78XH#138] opened 2021-09-12 14:06 UTC
Since the last major update in FS2020, I haven't been able to set the altimeter to standard. I have even tried switching back to the legacy mode for the ui controls and still can't click it like you used to be able to.

**Comment by DanP77** [comment] 2021-09-17 09:26
Duplicate of incident https://github.com/Heavy-Division/B78XH/issues/135

**Comment by kimlada** [comment] 2021-12-10 19:24
STD can be set by EFIS and last version has also fixed the knob

**Closed by kimlada** 2021-12-10 19:24 UTC
Labels: confirmed, fixed
