### ISSUE TITLE
MSFS 787 FMS heavy mod RTE request "LOAD FP FROM SB" does not load SID and STAR waypoints

### ISSUE THREAD

**Issue by MRAviator1** [Heavy-Division/B78XH#193] opened 2022-02-03 23:52 UTC
When I generate a flight plan from SimBrief I see the waypoints of the SID and STAR in the .PLN file but these do not load in the MSFS 787 Heavy Mod RTE request Load FP from SB. I see all the waypoints in LEGS between the SID and STAR but not the departure and arrival waypoints.  Is this a format issue? Any ideas how to get these into the 787 FMS?

I have selected the SID/STARs manually up till now but my end goal was a workaround to the KPDX scenery by FlightBeam (iBlueYonder) as they recently updated the scenery and changed the facilities data to exclude runways 3/21 and now I cannot select a STAR from the FMS or MSFS worldmap.

**Comment by landodragon141** [comment] 2022-02-08 21:19
Not importing SID/STAR from simbrief is generally considered working as intended. This is due to the fact that this has been reported to be real world behavior. With regards to the specific airport that sounds like an issue that needs to be addressed by that specific developer.

**Comment by nakajimayoshi** [comment] 2022-11-04 07:31
@MRAviator1 The SB importer has been updated to automatically include SID/STAR, try the latest DEV version

**Closed by nakajimayoshi** 2022-11-04 07:31 UTC
